export type WorkflowMaturity = 'implemented' | 'partial' | 'planned'
export type WorkflowPriority = 'foundation' | 'p0' | 'p1' | 'p2'
export type WorkflowNodeKind = 'deterministic' | 'llm_agent' | 'clinical_model' | 'retrieval' | 'validator' | 'governance' | 'offline'

export interface WorkflowNodeDefinition {
  id: string
  stageId: string
  titleZh: string
  titleEn: string
  description: string
  kind: WorkflowNodeKind
  maturity: WorkflowMaturity
  priority: WorkflowPriority
  inputs: string[]
  outputs: string[]
  why: string
  referenceLesson: string
  owlPathUpgrade: string
  validation: string
  dependsOn: string[]
}

export interface WorkflowStageDefinition {
  id: string
  number: string
  titleZh: string
  titleEn: string
  summary: string
  note: string
  nodeIds: string[]
}

export type ExpertConsultGroup = 'core' | 'dynamic'

export interface ExpertConsultDefinition {
  roleId: string
  group: ExpertConsultGroup
  titleZh: string
  titleEn: string
  responsibility: string
  inputs: string[]
  outputs: string[]
  triggers: string[]
  maturity: WorkflowMaturity
}

export const LATEST_WORKFLOW_DATE = '2026-08-14'
export const LATEST_WORKFLOW_LABEL = '候选验证闭环 × OwlPath时间化病原推演'

export const LATEST_WORKFLOW_STAGES: WorkflowStageDefinition[] = [
  {
    id: 'evidence_foundation',
    number: '01',
    titleZh: '冻结当前真正可见的临床证据',
    titleEn: 'Freeze decision-time clinical evidence',
    summary: '先回答“此刻医生究竟知道什么”，再谈病原体。原文保留，结构化结果只作为索引。',
    note: 'OwlPath原生优势：发生时间与可见时间分开，未来信息不能倒灌。',
    nodeIds: ['decision_time_ledger', 'clinical_evidence_compiler', 'infection_complexity_router'],
  },
  {
    id: 'candidate_recall',
    number: '02',
    titleZh: '从异质证据源扩大候选召回',
    titleEn: 'Recall candidates from heterogeneous evidence sources',
    summary: '不让一个LLM一次猜答案；临床视角、统计模型、流行先验、病例库与外部知识分别提出候选。',
    note: '学习公开研究系统的多路召回，但把遗传工具替换为感染专属模型、先验与病例库。',
    nodeIds: ['core_expert_consult_team', 'dynamic_expert_registry', 'structured_pathogen_model', 'dynamic_epidemiology_prior', 'local_similar_case_retrieval', 'syndrome_guideline_retrieval'],
  },
  {
    id: 'hypothesis_ledger',
    number: '03',
    titleZh: '建立暂定候选与患者级假设账本',
    titleEn: 'Build a preliminary candidate and hypothesis ledger',
    summary: '先保留Top-10至Top-15候选，提高罕见病原召回；统一Taxonomy后再进入逐项验证。',
    note: '账本记录候选如何出现、由哪些独立证据域支持，以及排名为何变化。',
    nodeIds: ['preliminary_candidate_union', 'taxonomy_normalizer', 'patient_hypothesis_ledger'],
  },
  {
    id: 'candidate_verification',
    number: '04',
    titleZh: '围绕每个候选分别找支持与反证',
    titleEn: 'Verify each candidate with supporting and opposing evidence',
    summary: '候选驱动检索发生在最终排名之前；支持、反对、差异和治疗干扰必须分开保存。',
    note: '这是相较当前运行链最重要的P0改造：不再“先定Top-5，再补参考文献”。',
    nodeIds: ['candidate_support_retrieval', 'candidate_counterevidence_retrieval', 'similar_case_difference_check', 'sampling_treatment_effect_check'],
  },
  {
    id: 'evidence_update',
    number: '05',
    titleZh: '核验证据并更新病原体假设',
    titleEn: 'Verify evidence and update pathogen hypotheses',
    summary: '不仅检查文献是否存在，还要判断它是否为人体证据、是否支持当前论断、证据权重是否合理。',
    note: '重点解决公开研究系统失败分析中“非特异证据权重过高”和“表型模拟病混淆”。',
    nodeIds: ['human_applicability_filter', 'semantic_entailment_verifier', 'causal_evidence_weighting', 'pathogen_hypothesis_updater'],
  },
  {
    id: 'final_reasoning',
    number: '06',
    titleZh: '总诊、反证与最有区分度的下一检查',
    titleEn: 'Final synthesis, challenge and discriminating next test',
    summary: '证据更新后才形成最终Top-5；独立审稿挑战遗漏、污染、定植、共感染和非感染解释。',
    note: '只有明确问题时允许一次定向修订；不会无限循环，也不会为了完成流程强造答案。',
    nodeIds: ['final_pathogen_synthesis', 'independent_counterevidence_critic', 'contamination_coinfection_challenger', 'discriminating_test_agent', 'bounded_revision'],
  },
  {
    id: 'output_and_science',
    number: '07',
    titleZh: '确定性结果合同与离线科学验证',
    titleEn: 'Deterministic output contract and offline scientific validation',
    summary: '最终结果必须可追溯、可复现、可比较；概率只有在真实数据校准后才能以概率发布。',
    note: 'DR.ECC用于开发与时间外验证，冻结系统后用MIMIC做地域外部验证。',
    nodeIds: ['deterministic_result_contract', 'calibration_open_set_layer', 'bilingual_trace_persistence', 'dual_database_validation', 'architecture_ablation'],
  },
]

export const LATEST_WORKFLOW_NODES: WorkflowNodeDefinition[] = [
  {
    id: 'decision_time_ledger', stageId: 'evidence_foundation', titleZh: 'T0 / ICU+24h临床事件账本', titleEn: 'T0 / ICU+24h Clinical Event Ledger',
    description: '冻结预测时点，分别记录事件发生时间、结果可见时间、来源和质量；只允许当时真正可见的信息进入推演。',
    kind: 'deterministic', maturity: 'partial', priority: 'foundation',
    inputs: ['急诊、住院及ICU时间轴', '病史、生命体征、检验、影像、治疗和待回检查', 'event_time与available_time'],
    outputs: ['不可变患者证据快照', '未来信息泄漏审计', '缺失与时间不确定标记'],
    why: '感染诊断高度依赖时间；培养采样时间不等于病原体结果已经可见。',
    referenceLesson: '保留原始输入与标准化表型并行使用。',
    owlPathUpgrade: '增加严格双时间、待回状态和抗菌治疗前后关系，避免回顾性信息倒灌。',
    validation: '任何输入事件必须满足available_time不晚于预测时点；无法精确判断者单独标记。',
    dependsOn: [],
  },
  {
    id: 'clinical_evidence_compiler', stageId: 'evidence_foundation', titleZh: '时间化临床证据编译器', titleEn: 'Temporal Clinical Evidence Compiler',
    description: '将原文切成稳定来源片段，同时识别否定、待回、冲突、趋势、标本部位和治疗影响；原文永不被结构化结果替代。',
    kind: 'deterministic', maturity: 'partial', priority: 'p0',
    inputs: ['冻结原文与结构化事件', '版本化医学术语表', '检验单位和参考范围'],
    outputs: ['source_fragment_id', '时间化感染证据事件', '否定、冲突和缺失信息清单'],
    why: 'LLM抽取可能遗漏“抓鱼、脑脊液、肝脓肿可能”等决定性线索。',
    referenceLesson: '先把自由文本标准化，再交给后续诊断工具。',
    owlPathUpgrade: '标准化只是索引；所有Agent仍可回到原文片段核验，避免抽取错误成为单点故障。',
    validation: '片段必须无损覆盖全文；引用只能指向冻结清单中存在的片段。',
    dependsOn: ['decision_time_ledger'],
  },
  {
    id: 'infection_complexity_router', stageId: 'evidence_foundation', titleZh: '感染/非感染与复杂度路由', titleEn: 'Infection / Non-infection and Complexity Router',
    description: '并行保留感染、非感染模拟病和开放集可能；固定召集五个核心专家，再根据综合征、宿主、暴露与器械线索最多选择六个动态专科。',
    kind: 'clinical_model', maturity: 'partial', priority: 'p1',
    inputs: ['时间化证据事件', '宿主、综合征、暴露和器械线索'],
    outputs: ['感染与非感染并行假设', '本次核心会诊组', '动态专科专家 selected / not_applicable 清单'],
    why: '开发模式可以始终给出五个病原假设，但不能让肺栓塞、药物性肺炎等模拟病从系统中消失。',
    referenceLesson: '根据任务状态选择工具，而不是所有工具无差别运行。',
    owlPathUpgrade: '从固定数量Agent改为可版本化专家登记表；路由状态进入可审计执行图，未选专家显示 not_applicable，不伪造意见。',
    validation: '路由规则、触发证据与未选原因必须可复现；每位专家的新增信息率与重复率必须单独评估。',
    dependsOn: ['clinical_evidence_compiler'],
  },
  {
    id: 'core_expert_consult_team', stageId: 'candidate_recall', titleZh: '核心顶尖临床专家会诊组', titleEn: 'Core Expert Consultation Team',
    description: '由感染科、临床流行病学、检验医学、临床微生物/细菌培养和重症医学构成默认会诊底座；角色是定义好的专业职责，不是只换一句身份设定。',
    kind: 'llm_agent', maturity: 'implemented', priority: 'p0',
    inputs: ['完整病例原文与冻结证据片段', '预测时点、待回结果和用药时间线', '各专业角色的输入/输出合同'],
    outputs: ['各专家的关键事实、矛盾和缺失', '具体病原候选池', '支持与反对片段ID', '需动态加会诊的专科建议'],
    why: '感染诊断不只是列病原体；样本质量、检测窗口、宿主与器官损伤会同时改变候选排名。',
    referenceLesson: '专用Agent Server围绕各自工具和数据源工作。',
    owlPathUpgrade: '将抽象证据视角升级为临床真实会诊职责；保存结构化专业意见，不保存或展示隐藏思维链。',
    validation: '必须比较核心会诊组与旧视角Agent在候选召回、证据准确性、重复率、延迟和费用上的净增益。',
    dependsOn: ['infection_complexity_router'],
  },
  {
    id: 'dynamic_expert_registry', stageId: 'candidate_recall', titleZh: '动态顶尖临床专科专家库', titleEn: 'Dynamic Elite Clinical Specialist Registry',
    description: '二十个动态角色覆盖放射、呼吸、消化、肝胆胰、泌尿、肾脏、神经、心血管、血液/免疫、移植、外科源控制、骨关节、皮肤软组织、妇产、儿科/新生儿、热带病/寄生虫、真菌、病毒/分子、抗菌药管理和医疗器械感染；每次最多召集六个。',
    kind: 'llm_agent', maturity: 'implemented', priority: 'p0',
    inputs: ['核心会诊初步意见', '解剖部位、宿主、暴露、器械与特殊人群路由信号', '专家版本、触发条件和调用预算'],
    outputs: ['每位专家 selected / not_applicable 状态', '专科特异候选和反证', '专科检查与标本建议', '未选原因和路由证据'],
    why: '不同病例需要的专家组合不同；固定把所有专科同时运行会增加噪声、重复和调用成本。',
    referenceLesson: '根据患者状态动态调度专用工具与知识源。',
    owlPathUpgrade: '专家注册表可版本化扩展；当前每次最多召集六个有明确触发证据的动态角色，未召集者不产生伪意见。',
    validation: '评估路由召回率、不必要召集率、少数专科漏召回、新增候选命中与单例总成本。',
    dependsOn: ['infection_complexity_router', 'core_expert_consult_team'],
  },
  {
    id: 'structured_pathogen_model', stageId: 'candidate_recall', titleZh: '结构化时间序列病原模型', titleEn: 'Structured Temporal Pathogen Model',
    description: '使用ICU+24小时内结构化生命体征、检验、器官支持和趋势，提供独立于LLM的病原候选与分数。',
    kind: 'clinical_model', maturity: 'planned', priority: 'p1',
    inputs: ['DR.ECC/MIMIC共同可得特征', '0/6/12/24小时序列', '冻结训练队列与标签'],
    outputs: ['分层病原候选', '模型原始分数', '缺失与适用性标记'],
    why: '语言模型擅长解释复杂文本，但不应独自承担概率估计。',
    referenceLesson: 'Exomiser等专用算法与LLM互补，而不是让LLM替代全部模型。',
    owlPathUpgrade: '训练、验证和外部测试患者隔离；模型分数在校准前明确不是概率。',
    validation: '报告Top-k、MRR、AUPRC、校准、亚组和时间外/地区外性能。',
    dependsOn: ['infection_complexity_router'],
  },
  {
    id: 'dynamic_epidemiology_prior', stageId: 'candidate_recall', titleZh: '医院、地区、季节与耐药动态先验', titleEn: 'Hospital, Regional, Seasonal and AMR Prior',
    description: '以受治理的聚合数据提供病原体流行基线，不将新闻搜索或未经验证的流行信号直接当作患者证据。',
    kind: 'clinical_model', maturity: 'planned', priority: 'p2',
    inputs: ['医院历史聚合病原谱', '地区与季节', '公共卫生监测', '感染部位与获得场景'],
    outputs: ['动态先验分布', '数据新鲜度和地域适用性', '耐药背景提示'],
    why: '同一综合征在不同医院和季节的病原谱并不相同。',
    referenceLesson: '利用外部数据库补足模型知识边界。',
    owlPathUpgrade: '先验与患者证据分开保存，不能用高流行率覆盖强烈的病例特异反证。',
    validation: '按医院、年份和季节做时间外验证，并审计先验漂移。',
    dependsOn: ['infection_complexity_router'],
  },
  {
    id: 'local_similar_case_retrieval', stageId: 'candidate_recall', titleZh: '本地相似感染病例检索', titleEn: 'Local Similar Infection Case Retrieval',
    description: '在受治理的DR.ECC/MIMIC病例库内进行向量召回、医学重排和关键差异核验；只返回去标识化结构化摘要。',
    kind: 'retrieval', maturity: 'planned', priority: 'p1',
    inputs: ['仅使用预测时点前信息的病例向量', '患者级隔离的开发/验证/测试索引'],
    outputs: ['相似病例列表', '共同点与关键差异', '检索覆盖和距离'],
    why: '公开研究系统消融显示相似病例在存在高质量类比时增益最大。',
    referenceLesson: 'Embedding初筛、医学Cross-Encoder重排、再判断临床相似性。',
    owlPathUpgrade: '全程本地；测试患者、同一患者其他住院和未来标签不能被检索回来。',
    validation: '执行case-bank-disentangled评测，单独报告近重复移除后的性能。',
    dependsOn: ['infection_complexity_router'],
  },
  {
    id: 'syndrome_guideline_retrieval', stageId: 'candidate_recall', titleZh: '综合征、指南与公共卫生检索', titleEn: 'Syndrome, Guideline and Public-health Retrieval',
    description: '用去标识化概念查询Europe PMC、PubMed、指南和公共卫生信号，不把病例全文发送给搜索接口。',
    kind: 'retrieval', maturity: 'partial', priority: 'foundation',
    inputs: ['综合征、暴露、宿主、解剖部位与获得场景概念'],
    outputs: ['初始知识证据', '来源状态和覆盖缺口', '可追溯PMID/DOI或权威来源ID'],
    why: '第一轮检索用于扩充候选，而不是提前证明某个答案。',
    referenceLesson: '先从患者表型广泛收集知识，再形成初步候选。',
    owlPathUpgrade: '查询最小化、来源白名单、单源失败隔离和明确的retrieval_partial。',
    validation: '查询日志必须可复现且不含病例原文、姓名、日期、电话或病历号。',
    dependsOn: ['infection_complexity_router'],
  },
  {
    id: 'preliminary_candidate_union', stageId: 'hypothesis_ledger', titleZh: '多路候选并集与暂定Top-10至15', titleEn: 'Multi-route Candidate Union and Preliminary Top-10 to 15',
    description: '合并临床Agent、结构化模型、动态先验、病例检索和知识检索提出的候选，先追求召回，再进入严格验证。',
    kind: 'deterministic', maturity: 'partial', priority: 'p0',
    inputs: ['各独立证据源的候选和来源', '证据域去重结果'],
    outputs: ['暂定候选并集', '候选来源和独立证据域', '候选覆盖缺口'],
    why: '低频病原体可能被任何单一路径漏掉；过早截成Top-5会降低召回。',
    referenceLesson: '综合诊断API、Web知识、相似病例与LLM候选。',
    owlPathUpgrade: '按独立证据域而非Agent数量计支持；类别词和Unknown不能占具体候选。',
    validation: '同一Taxon不能重复；候选池扩大会同时报告成本和噪声。',
    dependsOn: ['core_expert_consult_team', 'dynamic_expert_registry', 'structured_pathogen_model', 'dynamic_epidemiology_prior', 'local_similar_case_retrieval', 'syndrome_guideline_retrieval'],
  },
  {
    id: 'taxonomy_normalizer', stageId: 'hypothesis_ledger', titleZh: 'NCBI Taxonomy标准化与层级核验', titleEn: 'NCBI Taxonomy Normalization and Rank Verification',
    description: '统一拉丁学名、中文名、同义名、TaxID和物种层级；无法可靠解析时保留unresolved，绝不强行匹配。',
    kind: 'validator', maturity: 'implemented', priority: 'foundation',
    inputs: ['模型提出的规范拉丁名', '版本化本地术语表', 'NCBI Taxonomy核验结果'],
    outputs: ['可信TaxID与rank', '同义名去重', '安全解析原因码'],
    why: '“S. pneumoniae”和“Streptococcus pneumoniae”必须被识别为同一病原体。',
    referenceLesson: '用Orphanet/OMIM标准化疾病名称。',
    owlPathUpgrade: '不使用无阈值最近邻强配；名称、TaxID和具体rank必须一致。',
    validation: '只接受物种、物种复合群或明确病毒型别；跨TaxID别名冲突必须拒绝。',
    dependsOn: ['preliminary_candidate_union'],
  },
  {
    id: 'patient_hypothesis_ledger', stageId: 'hypothesis_ledger', titleZh: '患者级病原体假设账本', titleEn: 'Patient-level Pathogen Hypothesis Ledger',
    description: '为每个候选保存支持、反对、中性、未知和冲突证据，以及来源时间、可靠度、区分度和排名变化。',
    kind: 'deterministic', maturity: 'planned', priority: 'p0',
    inputs: ['标准化候选', '患者证据片段', '独立证据域和初始检索证据'],
    outputs: ['候选—证据矩阵', '排名变化历史', '仍需验证的问题清单'],
    why: '这是系统的运行内“记忆”，让后续检索和反思围绕明确假设而不是自由文本展开。',
    referenceLesson: '中央Memory Bank避免重复检索并保存中间证据。',
    owlPathUpgrade: '记忆变成不可变、结构化、患者级账本；不保存隐藏思维链，也不跨患者混用。',
    validation: '每个结论必须回指冻结片段或已核验外部来源；所有更新保留版本和哈希。',
    dependsOn: ['taxonomy_normalizer'],
  },
  {
    id: 'candidate_support_retrieval', stageId: 'candidate_verification', titleZh: '逐候选支持证据检索', titleEn: 'Candidate-specific Supporting Evidence Retrieval',
    description: '针对每个TaxID分别查询暴露、宿主、感染部位、影像和实验室表型是否与该病原体相符。',
    kind: 'retrieval', maturity: 'partial', priority: 'p0',
    inputs: ['标准化候选', '去标识化病例概念', '本地知识镜像和权威外部来源'],
    outputs: ['候选特异支持来源', '查询与命中覆盖', '未命中原因'],
    why: '候选生成后的第二轮检索比一次通用RAG更具区分力。',
    referenceLesson: '对每个暂定疾病重新检索Orphanet、OMIM、PubMed等证据。',
    owlPathUpgrade: '必须在最终排名之前运行，并能真实改变候选权重。',
    validation: '来源ID由系统生成；不得接受模型编造的PMID、DOI或URL。',
    dependsOn: ['patient_hypothesis_ledger'],
  },
  {
    id: 'candidate_counterevidence_retrieval', stageId: 'candidate_verification', titleZh: '逐候选反证与替代解释检索', titleEn: 'Candidate-specific Counter-evidence and Alternative Retrieval',
    description: '主动寻找该候选不应成立的条件、竞争病原体和非感染替代解释，降低确认偏倚。',
    kind: 'retrieval', maturity: 'planned', priority: 'p0',
    inputs: ['候选特异支持证据', '病例中的反对与缺失线索'],
    outputs: ['反证来源', '替代病原体或非感染解释', '需要下调的候选'],
    why: '只检索支持材料会让系统越来越相信第一轮猜测。',
    referenceLesson: 'Self-reflection明确判断候选Correct或Incorrect。',
    owlPathUpgrade: '反证不由原总诊模型自由发挥，而由独立查询计划和结构化合同产生。',
    validation: '每个高位候选至少记录一次反证搜索，即使结果为未找到。',
    dependsOn: ['patient_hypothesis_ledger'],
  },
  {
    id: 'similar_case_difference_check', stageId: 'candidate_verification', titleZh: '相似病例共同点与关键差异核验', titleEn: 'Similar-case Commonality and Difference Check',
    description: '比较相似病例与当前患者的决定性差异，防止“看起来像”被误当作病原体证据。',
    kind: 'validator', maturity: 'planned', priority: 'p1',
    inputs: ['本地相似病例', '当前患者冻结证据', '候选病原体'],
    outputs: ['共同点', '关键差异', '病例类比适用性'],
    why: '病例检索可能因近重复或共享非特异重症表现获得虚假高相似度。',
    referenceLesson: 'MedCPT重排后再由轻量LLM判断病例是否相关。',
    owlPathUpgrade: '强制展示差异；相似病例只是一个证据域，不能直接决定结果。',
    validation: '移除同患者、近重复及标签泄漏后重新报告病例检索增益。',
    dependsOn: ['patient_hypothesis_ledger', 'local_similar_case_retrieval'],
  },
  {
    id: 'sampling_treatment_effect_check', stageId: 'candidate_verification', titleZh: '标本、抗菌药与检出率影响检查', titleEn: 'Sampling, Antimicrobial and Detectability Check',
    description: '判断标本是否在用药前采集、培养何时可见、当前药物覆盖是否会造成假阴性或选择性检出。',
    kind: 'deterministic', maturity: 'partial', priority: 'p0',
    inputs: ['标本采集和报告时间', '实际给药时间', '候选病原体与检测方式'],
    outputs: ['检出率影响说明', '阴性结果的可解释性', '下一次采样建议'],
    why: '阴性培养不等于没有病原体，尤其是在经验抗菌治疗之后。',
    referenceLesson: '根据缺失的决定性检查解释候选为何难以区分。',
    owlPathUpgrade: '将治疗和取样视为证据生成机制的一部分，而不只是病例背景。',
    validation: '医嘱与实际给药分开；采样时间与结果可见时间分开。',
    dependsOn: ['patient_hypothesis_ledger'],
  },
  {
    id: 'human_applicability_filter', stageId: 'evidence_update', titleZh: '人体临床适用性与来源去重', titleEn: 'Human Clinical Applicability and Source Deduplication',
    description: '排除动物、养殖或体外研究被误当成人体病例证据，并按PMID/DOI合并跨来源重复记录。',
    kind: 'validator', maturity: 'partial', priority: 'p0',
    inputs: ['文献题名、来源、标识符和研究语境'],
    outputs: ['人体适用来源', '跨库去重结果', '证据范围标签'],
    why: '病原名出现在鱼类或动物实验题名中，并不支持人类感染候选。',
    referenceLesson: '提供可访问的参考链接和来源列表。',
    owlPathUpgrade: '不把URL可访问等同于医学有效；先核对宿主、研究类型和来源身份。',
    validation: '同一PMID/DOI只计一次；非人类研究必须有明确的人体适用理由才能绑定。',
    dependsOn: ['candidate_support_retrieval', 'candidate_counterevidence_retrieval'],
  },
  {
    id: 'semantic_entailment_verifier', stageId: 'evidence_update', titleZh: '摘要级医学蕴含核验', titleEn: 'Abstract-level Medical Entailment Verification',
    description: '检查文献摘要是否真正支持“该暴露、宿主、综合征与候选病原体相关”这一具体论断，而非仅有关键词重叠。',
    kind: 'validator', maturity: 'planned', priority: 'p0',
    inputs: ['候选—证据主张', '可合法获取的摘要或指南原文', '来源权威性和时效'],
    outputs: ['支持、反对、中性或无法判断', '可引用原句位置', '证据直接性等级'],
    why: '题名包含病原名不等于文章支持当前病例中的因果关系。',
    referenceLesson: '医生审核参考来源是否可靠且与判断相关。',
    owlPathUpgrade: '将引用核验变成可重复的机器与人工联合任务，而不是只做HTTP可达性检查。',
    validation: '定期由医生盲评蕴含正确率；错误引用不能进入候选支持分数。',
    dependsOn: ['human_applicability_filter'],
  },
  {
    id: 'causal_evidence_weighting', stageId: 'evidence_update', titleZh: '病原特异性与因果证据权重层', titleEn: 'Pathogen-specific and Causal Evidence Weighting',
    description: '区分病原特异线索、综合征支持、宿主先验、继发器官损伤、治疗后改变和偶然异常。',
    kind: 'clinical_model', maturity: 'planned', priority: 'p0',
    inputs: ['患者证据矩阵', '可获得的外部证据与检索覆盖状态', '候选间共同与差异性线索'],
    outputs: ['证据类别', '支持/反对方向', '区分度和可信度'],
    why: '公开研究反复提示：非特异指标可能压过决定性线索，因此必须显式核验证据权重。',
    referenceLesson: '逐候选反思暴露了证据权重，而不仅是知识缺失。',
    owlPathUpgrade: '显式区分“支持感染”与“区分具体病原体”，避免CRP/PCT被重复用于所有候选。',
    validation: '医生盲评证据类别和方向；报告高权重错误率与候选排名敏感性。',
    dependsOn: ['semantic_entailment_verifier', 'similar_case_difference_check', 'sampling_treatment_effect_check'],
  },
  {
    id: 'pathogen_hypothesis_updater', stageId: 'evidence_update', titleZh: '患者级病原体假设更新器', titleEn: 'Patient-level Pathogen Hypothesis Updater',
    description: '综合当前患者证据、病例类比、外部证据和先验，更新各候选相容性；保留Unknown、非感染和共感染。',
    kind: 'clinical_model', maturity: 'planned', priority: 'p2',
    inputs: ['加权证据矩阵', '动态先验', '结构化模型输出', '开放集与共感染状态'],
    outputs: ['更新后的候选排序依据', '冲突和剩余不确定性', '需要区分的候选对'],
    why: '最终排序应由证据变化驱动，而不是让总诊LLM重新自由生成一遍。',
    referenceLesson: '证据不支持候选时返回更深一轮搜索。',
    owlPathUpgrade: '更新过程有边界、有版本、可回滚；未来可实现P(证据|病原体)世界模型。',
    validation: '先以结构化规则和消融验证，拥有真实数据后再校准为概率模型。',
    dependsOn: ['causal_evidence_weighting', 'structured_pathogen_model', 'dynamic_epidemiology_prior'],
  },
  {
    id: 'final_pathogen_synthesis', stageId: 'final_reasoning', titleZh: '证据更新后的最终病原体总诊', titleEn: 'Evidence-updated Final Pathogen Synthesis',
    description: '在候选已标准化并完成支持/反证核验后，形成五个具体、唯一、可追溯的病原体假设。',
    kind: 'llm_agent', maturity: 'partial', priority: 'p0',
    inputs: ['更新后的候选账本', '病例片段', '核验文献和相似病例差异'],
    outputs: ['最终Top-5', '每项支持与反对证据', 'Unknown与共感染分开表达'],
    why: '总诊负责医学综合和表达，但不能跳过前面的确定性证据核验。',
    referenceLesson: '中央Host负责最终综合，而专用服务器提供证据。',
    owlPathUpgrade: '把总诊从“第一次直接定Top-5”改成“证据更新后的最终排序者”。',
    validation: '最终候选必须来自已验证候选池；大类词、Unknown和重复物种不能占Top-5。',
    dependsOn: ['pathogen_hypothesis_updater'],
  },
  {
    id: 'independent_counterevidence_critic', stageId: 'final_reasoning', titleZh: '独立反证审稿', titleEn: 'Independent Counter-evidence Critic',
    description: '从遗漏、替代解释、证据错配和确认偏倚挑战最终候选，优先使用不同模型指纹或全新上下文。',
    kind: 'llm_agent', maturity: 'implemented', priority: 'foundation',
    inputs: ['最终Top-5', '冻结病例证据', '候选证据账本'],
    outputs: ['接受或明确问题清单', '需要修订的结构化理由'],
    why: '同一个模型既提出答案又证明自己正确，容易放大相关错误。',
    referenceLesson: '在最终输出前对候选逐项进行Correct/Incorrect反思。',
    owlPathUpgrade: '审稿上下文独立，客观问题再由确定性验证器复核，原始意见保留审计。',
    validation: '分别报告有效审稿问题、被确定性驳回的幻觉问题和修订增益。',
    dependsOn: ['final_pathogen_synthesis'],
  },
  {
    id: 'contamination_coinfection_challenger', stageId: 'final_reasoning', titleZh: '污染、定植、共感染与非感染挑战者', titleEn: 'Contamination, Colonization, Coinfection and Mimic Challenger',
    description: '专门检查培养分离物是否为责任病原、是否存在多病原共同解释，以及非感染模拟病是否更合理。',
    kind: 'llm_agent', maturity: 'planned', priority: 'p1',
    inputs: ['标本部位与采样背景', '多病原候选', '感染/非感染并行假设'],
    outputs: ['污染/定植风险', '共感染组合', '非感染竞争解释'],
    why: '感染任务不是静态单标签分类；阳性培养也不自动等于致病病原。',
    referenceLesson: '针对临床表型模拟病进行候选反思。',
    owlPathUpgrade: '把感染特有的污染、定植和共感染变成独立挑战职责。',
    validation: '与分层A/B/C病原学真值和双人临床仲裁对照。',
    dependsOn: ['final_pathogen_synthesis'],
  },
  {
    id: 'discriminating_test_agent', stageId: 'final_reasoning', titleZh: '最有区分度的下一检查', titleEn: 'Most Discriminating Next Test',
    description: '比较排名靠前候选最关键的证据差异，推荐能最大幅度区分它们且现实可执行的下一项检查。',
    kind: 'clinical_model', maturity: 'partial', priority: 'p1',
    inputs: ['候选对及关键缺失证据', '检测灵敏度、标本、周转时间、抗菌药影响和可及性'],
    outputs: ['下一检查及理由', '预期能区分的候选', '执行条件和局限'],
    why: '公开病例研究提示：缺少关键检查时，系统应指出缺口，而不是假装已有答案。',
    referenceLesson: '失败分析揭示决定性缺失检查的重要性。',
    owlPathUpgrade: '从通用“再做PCR”升级为候选对驱动、受本地可及性约束的检查建议。',
    validation: '在真实队列中回放检查结果，测量排名变化；未验证前只展示为研发建议。',
    dependsOn: ['final_pathogen_synthesis', 'pathogen_hypothesis_updater'],
  },
  {
    id: 'bounded_revision', stageId: 'final_reasoning', titleZh: '最多一次定向修订', titleEn: 'At Most One Targeted Revision',
    description: '只有结构化审稿问题或确定性合同问题存在时，才允许总诊在冻结证据范围内修订一次。',
    kind: 'llm_agent', maturity: 'implemented', priority: 'foundation',
    inputs: ['保留的有效审稿问题', '原有效草案', '新增核验证据'],
    outputs: ['修订稿或保留原有效稿', '修订事务决策记录'],
    why: '无限反思会增加成本，并可能把不确定性逐渐改写成过度确定。',
    referenceLesson: '证据不支持候选时允许重新检索和重排。',
    owlPathUpgrade: '循环有硬预算；无效修订不能覆盖先前已经合同有效的结果。',
    validation: '记录修订触发率、改进率、损害率、调用成本和是否完成二次复核。',
    dependsOn: ['independent_counterevidence_critic', 'contamination_coinfection_challenger', 'discriminating_test_agent'],
  },
  {
    id: 'deterministic_result_contract', stageId: 'output_and_science', titleZh: '确定性Top-5与证据合同', titleEn: 'Deterministic Top-5 and Evidence Contract',
    description: '检查恰好五个具体且唯一病原体、TaxID、排序、片段、Agent来源、文献引用和结果完整性哈希。',
    kind: 'validator', maturity: 'implemented', priority: 'foundation',
    inputs: ['最终或修订后的病原体结果', '冻结片段与来源注册表'],
    outputs: ['合同有效结果或技术失败', '安全错误码与验证详情'],
    why: '自由文本和正则表达式不能承担核心医学输出合同。',
    referenceLesson: '疾病名称标准化和参考链接验证。',
    owlPathUpgrade: '所有核心字段由本地Schema和术语服务器核验，不相信模型自报的TaxID或校准状态。',
    validation: '合同失败不得用通用词表伪造候选；失败必须进入评测分母。',
    dependsOn: ['bounded_revision'],
  },
  {
    id: 'calibration_open_set_layer', stageId: 'output_and_science', titleZh: '校准、开放集与Conformal层', titleEn: 'Calibration, Open-set and Conformal Layer',
    description: '把未校准模型分数与经外部验证的概率分开，独立表达Unknown、非感染、共感染和预测集合覆盖率。',
    kind: 'clinical_model', maturity: 'planned', priority: 'p2',
    inputs: ['冻结模型输出', '开发与外部验证队列', '亚组和分布漂移信息'],
    outputs: ['校准概率或明确未校准状态', '开放集分数', '覆盖率受控的预测集合'],
    why: '0.30的LLM自报分数不能称为30%概率。',
    referenceLesson: 'Top-k排序适合候选召回，但不等于临床概率。',
    owlPathUpgrade: '可靠性裁决独立于生成答案的模型，并按医院、时间和亚组验证。',
    validation: '报告Brier、ECE、覆盖率、集合大小、OOD和关键亚组性能。',
    dependsOn: ['deterministic_result_contract'],
  },
  {
    id: 'bilingual_trace_persistence', stageId: 'output_and_science', titleZh: '双语结果、完整轨迹与版本签名', titleEn: 'Bilingual Result, Full Trace and Version Signature',
    description: '中文主行、英文副行共享同一套结构化数值；冻结执行图、模型、输入、证据、节点工件和哈希。',
    kind: 'deterministic', maturity: 'implemented', priority: 'foundation',
    inputs: ['合同有效结果', '执行图与节点工件', '版本化医学术语表'],
    outputs: ['医生可读结果', '逐节点轨迹', '可复现运行身份'],
    why: '比赛展示和科学验证都需要知道系统究竟做了什么，而不是只看最终答案。',
    referenceLesson: '保存中间诊断、检索结果、病例匹配与最终输出。',
    owlPathUpgrade: '结构化轨迹替代自由思维链；API Key、原始Provider响应和真实病例原文不经轨迹暴露。',
    validation: '刷新和复制URL不串病例；manifest、artifact和result哈希可独立重算。',
    dependsOn: ['deterministic_result_contract', 'calibration_open_set_layer'],
  },
  {
    id: 'dual_database_validation', stageId: 'output_and_science', titleZh: 'DR.ECC开发与MIMIC冻结外部验证', titleEn: 'DR.ECC Development and Frozen MIMIC External Validation',
    description: 'DR.ECC用于开发和时间外验证；锁定队列、提示词、术语表与阈值后，在MIMIC做独立地域外部验证。',
    kind: 'offline', maturity: 'planned', priority: 'p1',
    inputs: ['ICU+24小时输入快照', 'A/B级病原学真值', '污染/定植/共感染仲裁'],
    outputs: ['队列流图', 'Top-k与MRR', '技术失败率、延迟、证据正确率和亚组结果'],
    why: '纯虚构病例只能证明工程跑通，不能证明病原体预测正确。',
    referenceLesson: '跨数据集、跨中心、医生审核和真实病例评测。',
    owlPathUpgrade: '严格landmark和available_time；MIMIC患者级数据只在获批本地环境运行。',
    validation: '患者级隔离；所有失败留在分母；冻结后只做一次外部测试。',
    dependsOn: ['bilingual_trace_persistence'],
  },
  {
    id: 'architecture_ablation', stageId: 'output_and_science', titleZh: '架构消融与医生盲评', titleEn: 'Architecture Ablation and Blinded Clinician Review',
    description: '在同病例、同模型、同Token/费用预算下比较单LLM、文献、病例库、候选反思和完整OwlPath。',
    kind: 'offline', maturity: 'planned', priority: 'p0',
    inputs: ['冻结测试集', '各消融版本运行结果', '医生证据蕴含与临床相关性评分'],
    outputs: ['模块真实增益', '错误分类', '成本—性能曲线', '是否值得保留某个Agent'],
    why: '方框更多不等于系统更强，只有消融才能证明每个模块贡献了独立信息。',
    referenceLesson: '完整系统与移除病例检索、反思、Web知识的对照实验。',
    owlPathUpgrade: '加入时间泄漏、近重复病例、证据蕴含、技术失败和成本等更严格指标。',
    validation: '预注册主要指标与比较方案，公开代码、队列定义和聚合结果。',
    dependsOn: ['dual_database_validation'],
  },
]

export const EXPERT_CONSULT_REGISTRY: ExpertConsultDefinition[] = [
  {
    roleId: 'infectious_diseases', group: 'core', titleZh: '感染科首席专家', titleEn: 'Infectious Diseases Lead', maturity: 'implemented',
    responsibility: '统合感染综合征、宿主、暴露、病原学和已用治疗，组织病原体鉴别诊断与反证。',
    inputs: ['病例全文与T时点证据', '其他已召集专家的结构化意见'],
    outputs: ['优先综合征与具体病原候选', '关键支持/反对证据及会诊缺口'],
    triggers: ['核心候选；由路由器对本次病例标记 selected 或 not_applicable'],
  },
  {
    roleId: 'clinical_epidemiology', group: 'core', titleZh: '临床流行病学专家', titleEn: 'Clinical Epidemiology Expert', maturity: 'implemented',
    responsibility: '判断暴露的真实性与时间关系，区分个体证据、地区季节先验和未核实流行信号。',
    inputs: ['居住/旅行/职业/动物/食物/水体暴露', '发病日期、地区、季节和获得场景'],
    outputs: ['可信暴露链与矛盾', '经治理流行先验及候选修正方向'],
    triggers: ['核心候选；有暴露、聚集、地理或季节线索时优先 selected'],
  },
  {
    roleId: 'laboratory_medicine', group: 'core', titleZh: '检验医学专家', titleEn: 'Laboratory Medicine Expert', maturity: 'implemented',
    responsibility: '审核检验单位、时序、分析前误差、结果冲突和病理生理模式，避免将非特异重症反应当作病原证据。',
    inputs: ['血液学、生化、凝血、炎症、血气及趋势', '标本时间、参考范围和分析质量线索'],
    outputs: ['可靠检验模式与异常组合', '分析局限、复核需求和鉴别价值'],
    triggers: ['核心候选；检验异常、单位冲突或趋势影响排名时 selected'],
  },
  {
    roleId: 'clinical_microbiology_culture', group: 'core', titleZh: '临床微生物与细菌培养实验室专家', titleEn: 'Clinical Microbiology and Culture Laboratory Expert', maturity: 'implemented',
    responsibility: '审核标本部位与质量、革兰染色、培养/鉴定/药敏、报告时间、污染与定植，及用药对检出率的影响。',
    inputs: ['所有微生物标本、方法、已回/待回/阴性结果', '采样与抗感染用药时间线'],
    outputs: ['标本适配性与检出率解读', '具体病原候选、污染/定植风险及优先补检'],
    triggers: ['核心候选；存在培养、分子、镜检或用药干扰时优先 selected'],
  },
  {
    roleId: 'critical_care_emergency', group: 'core', titleZh: '重症与急诊医学专家', titleEn: 'Critical Care and Emergency Medicine Expert', maturity: 'implemented',
    responsibility: '重建器官衰竭和干预时间线，识别感染源控制需求、重症并发症与非感染模拟病。',
    inputs: ['生命体征、器官支持、乳酸、尿量与器官功能趋势', '采样、液体、血管活性药、呼吸支持和源控制'],
    outputs: ['器官损伤图谱与当前严重度', '与病原鉴别相关的器官模式和紧急缺口'],
    triggers: ['核心候选；存在器官支持、休克或多器官损伤时 selected'],
  },
  {
    roleId: 'radiology', group: 'dynamic', titleZh: '放射影像专家', titleEn: 'Radiology Expert', maturity: 'implemented',
    responsibility: '按解剖部位、形态和分布解读影像报告，区分原发灶、播散灶、并发症和模拟病。',
    inputs: ['CT/MRI/超声/胸片报告与时序', '疑似综合征和候选病原'],
    outputs: ['影像模式、主要部位与播散路径', '支持/反对候选及需进一步影像'],
    triggers: ['存在影像报告、多部位病灶或源控制问题时 selected'],
  },
  {
    roleId: 'pulmonology', group: 'dynamic', titleZh: '呼吸与危重呼吸专家', titleEn: 'Pulmonology Expert', maturity: 'implemented',
    responsibility: '鉴别肺炎、肺脓肿、吸入、弥漫性肺损伤及非感染性肺浸润，评估呼吸道标本。',
    inputs: ['呼吸症状、氧合/通气、胸部影像', '痰、气道吸引物、BAL及胸水资料'],
    outputs: ['呼吸综合征与具体病原候选', '标本优先级、支持/反对证据和模拟病'],
    triggers: ['肺部病灶、低氧、通气支持或呼吸道标本时 selected'],
  },
  {
    roleId: 'gastroenterology', group: 'dynamic', titleZh: '消化内科专家', titleEn: 'Gastroenterology Expert', maturity: 'implemented',
    responsibility: '分析胃肠道症状、肠炎、肠梗阻、腹膜炎和肠源性菌血症可能。',
    inputs: ['腹部症状、粪便检测、内镜与腹部影像', '手术、营养、抗生素与医疗暴露'],
    outputs: ['消化道感染定位与病原候选', '非感染替代解释及优先标本/检查'],
    triggers: ['腹泻、腹痛、呕吐、肠壁病变、腹膜刺激或肠梗阻时 selected'],
  },
  {
    roleId: 'urology', group: 'dynamic', titleZh: '泌尿外科与复杂尿路感染专家', titleEn: 'Urology and Complicated UTI Expert', maturity: 'implemented',
    responsibility: '识别梗阻性肾盂肾炎、前列腺感染、尿路器械相关感染与需要引流的源控制问题。',
    inputs: ['尿液、尿培养、泌尿系影像', '尿管、结石、梗阻、手术与器械史'],
    outputs: ['尿源感染可能性与具体候选', '污染/定植评估、引流与采样建议'],
    triggers: ['尿检异常、尿路症状、梗阻、结石或尿路器械时 selected'],
  },
  {
    roleId: 'neurology_neuroinfection', group: 'dynamic', titleZh: '神经内科与神经感染专家', titleEn: 'Neurology and Neuroinfection Expert', maturity: 'implemented',
    responsibility: '定位脑膜、脑实质、脊髓或周围神经病变，解读脑脊液并主动保留非感染神经急症。',
    inputs: ['意识、抽搐、局灶体征与神经影像', '脑脊液压力、细胞、生化、染色、培养和分子检测'],
    outputs: ['神经解剖定位与具体病原候选', '脑脊液局限、模拟病和鉴别性复查'],
    triggers: ['意识改变、脑膜刺激、抽搐、局灶征或脑脊液资料时 selected'],
  },
  {
    roleId: 'cardiology_endocarditis', group: 'dynamic', titleZh: '心血管与心内膜炎专家', titleEn: 'Cardiology and Endocarditis Expert', maturity: 'implemented',
    responsibility: '鉴别感染性心内膜炎、心肌炎、心包炎、感染性栓塞与非感染性心肌损伤。',
    inputs: ['杂音、栓塞征象、ECG、心肌标志物和超声', '血培养、器械/瓣膜史与血流动力学'],
    outputs: ['心血管感染综合征与候选', '心超/重复血培养需求及模拟病'],
    triggers: ['持续菌血症、心脏器械/瓣膜、栓塞、心肌损伤或心包表现时 selected'],
  },
  {
    roleId: 'nephrology', group: 'dynamic', titleZh: '肾脏内科专家', titleEn: 'Nephrology Expert', maturity: 'implemented',
    responsibility: '区分感染相关AKI、血栓性微血管病、肾炎、药物损伤和横纹肌溶解，判断肾损伤对病原鉴别的价值。',
    inputs: ['肌酐、尿量、尿沉渣、电解质、CK及溶血线索', '药物、低灌注、透析和肾脏基线'],
    outputs: ['AKI表型及其病原区分度', '肾毒性干扰、特异性检查和模拟病'],
    triggers: ['AKI、尿沉渣异常、溶血/血小板减少、横纹肌溶解或透析时 selected'],
  },
  {
    roleId: 'hepatobiliary_pancreatic', group: 'dynamic', titleZh: '肝胆胰专家', titleEn: 'Hepatobiliary and Pancreatic Expert', maturity: 'implemented',
    responsibility: '鉴别肝脏灶、胆道感染、肝炎、胰腺炎及缺血/药物性肝损伤，评估引流与源控制。',
    inputs: ['肝功能模式、胆汁淤积指标、凝血与病毒学', '腹部超声/CT/MRI、胆道操作和肝脏灶'],
    outputs: ['肝胆胰感染源与候选', '非感染性肝损伤反证及优先引流/采样'],
    triggers: ['明显转氨酶/胆红素异常、肝脏灶、胆道扩张或胰腺病变时 selected'],
  },
  {
    roleId: 'hematology_immunology', group: 'dynamic', titleZh: '血液与临床免疫专家', titleEn: 'Hematology and Clinical Immunology Expert', maturity: 'implemented',
    responsibility: '解读细胞减少、溶血、凝血障碍、免疫缺陷与炎症过度激活，识别血液病及自身免疫模拟。',
    inputs: ['血细胞、血涂片、溶血、凝血、铁蛋白和免疫学', '血液恶性肿瘤、化疗、生物制剂和免疫缺陷史'],
    outputs: ['免疫表型与机会感染候选', '血液/免疫模拟病和特异性检查'],
    triggers: ['严重细胞减少、溶血、DIC/TMA、血液病或免疫缺陷时 selected'],
  },
  {
    roleId: 'surgery_source_control', group: 'dynamic', titleZh: '外科与源控制专家', titleEn: 'Surgery and Source-control Expert', maturity: 'implemented',
    responsibility: '识别腹腔、软组织、伤口、吻合口、坏死组织和深部脓肿等需要手术或介入的感染源。',
    inputs: ['手术/创伤史、体格检查、伤口与引流资料', '影像、组织灌注、坏死与气体征象'],
    outputs: ['需源控制的解剖灶与候选', '手术/介入采样优先级及不能延误的线索'],
    triggers: ['创伤、近期手术、深部脓肿、穿孔、坏死性软组织感染或引流问题时 selected'],
  },
  {
    roleId: 'obstetrics_gynecology', group: 'dynamic', titleZh: '妇产科感染专家', titleEn: 'Obstetric and Gynecologic Infection Expert', maturity: 'implemented',
    responsibility: '按孕期、产后、流产/器械操作和盆腔解剖评估妇产科感染源及孕产妇特异风险。',
    inputs: ['妊娠周数、产程/产后时间线、宫腔/盆腔操作', '妇科症状、影像、培养与胎儿资料'],
    outputs: ['妇产科感染综合征与候选', '母胎安全相关检查、采样和模拟病'],
    triggers: ['妊娠、产后、流产、盆腔感染或妇科手术/器械时 selected'],
  },
  {
    roleId: 'pediatrics_neonatology', group: 'dynamic', titleZh: '儿科、新生儿与儿童感染专家', titleEn: 'Pediatrics, Neonatology and Pediatric Infection Expert', maturity: 'implemented',
    responsibility: '使用年龄特异生理、围产暴露、免疫发育、疫苗和儿童综合征解读病原谱。',
    inputs: ['出生/年龄、围产史、生长发育和疫苗', '年龄特异生命体征、检验、影像和暴露'],
    outputs: ['年龄特异综合征与病原候选', '儿童适配的检查、标本和安全注意'],
    triggers: ['新生儿、儿童或青少年病例时 selected；成人病例为 not_applicable'],
  },
  {
    roleId: 'transplant_infectious_diseases', group: 'dynamic', titleZh: '移植感染专家', titleEn: 'Transplant Infectious Diseases Expert', maturity: 'implemented',
    responsibility: '依移植类型、术后阶段、免疫抑制强度、供者/受者风险和预防方案重建机会感染谱。',
    inputs: ['移植类型与日期、免疫抑制和排斥治疗', '预防用药、供受者病毒学和器官功能'],
    outputs: ['移植阶段特异病原候选', '预防突破、再激活与优先检查建议'],
    triggers: ['实体器官/造血干细胞移植、捐献者暴露或移植特异免疫抑制时 selected'],
  },
  {
    roleId: 'medical_mycology', group: 'dynamic', titleZh: '医学真菌专家', titleEn: 'Medical Mycology Expert', maturity: 'implemented',
    responsibility: '根据宿主、解剖模式、抗原/抗体/培养/组织学和抗真菌用药解读侵袭性真菌病、定植与污染。',
    inputs: ['免疫状态、中性粒细胞、器械和长期抗生素', '真菌学标本、GM/BDG/抗原、培养、镜检和组织学'],
    outputs: ['具体真菌候选与侵袭性证据等级', '定植/污染反证、标本和检测窗口建议'],
    triggers: ['免疫抑制、持续发热、结节/空洞、真菌学信号或高风险器械时 selected'],
  },
  {
    roleId: 'tropical_medicine_parasitology', group: 'dynamic', titleZh: '热带病与寄生虫专家', titleEn: 'Tropical Medicine and Parasitology Expert', maturity: 'implemented',
    responsibility: '以地理、旅行、媒介、食物/水体和嗜酸细胞等线索识别热带病、寄生虫病及其检测窗口。',
    inputs: ['旅行/居住地、媒介、水体、生食、动物与职业暴露', '血涂片、嗜酸细胞、粪检、血清学和影像'],
    outputs: ['具体热带病/寄生虫候选', '暴露矛盾、适宜标本和定时重复检测建议'],
    triggers: ['流行地区、旅行、媒介、水体/生食、嗜酸细胞或不明原因周期热时 selected'],
  },
  {
    roleId: 'antimicrobial_stewardship', group: 'dynamic', titleZh: '抗菌药物管理与临床药学专家', titleEn: 'Antimicrobial Stewardship and Clinical Pharmacology Expert', maturity: 'implemented',
    responsibility: '判断已用药的病原覆盖、组织穿透、剂量暴露、检出率干扰和耐药选择压力，但不代替医生开立处方。',
    inputs: ['抗感染药物、剂量、给药时间与采样关系', '肾肝功能、药敏、药物浓度及本地耐药背景'],
    outputs: ['候选病原的覆盖/未覆盖解读', '诊断检出率干扰、耐药风险与需复核的药理问题'],
    triggers: ['已使用抗菌/抗真菌/抗病毒药、疑似耐药、器官功能改变或已回药敏时 selected'],
  },
  {
    roleId: 'orthopedics_bone_joint', group: 'dynamic', titleZh: '骨科与骨关节感染专家', titleEn: 'Orthopedics and Bone-joint Infection Expert', maturity: 'implemented',
    responsibility: '鉴别骨髓炎、化脓性关节炎、植入物相关感染和深部脊柱感染，评估穿刺、活检与外科源控制。',
    inputs: ['局部疼痛/肿胀、外伤/手术/内固定史', 'MRI/CT/核医学、关节液、骨/组织培养'],
    outputs: ['骨关节感染定位与具体候选', '植入物、采样和源控制建议'],
    triggers: ['骨/关节疼痛、脊柱症状、骨科手术/植入物或骨破坏影像时 selected'],
  },
  {
    roleId: 'dermatology_soft_tissue', group: 'dynamic', titleZh: '皮肤科与软组织感染专家', titleEn: 'Dermatology and Soft-tissue Infection Expert', maturity: 'implemented',
    responsibility: '识别皮损形态、入口、蜚皮癖、坏死性软组织感染、水体/动物暴露相关皮肤感染及非感染模拟。',
    inputs: ['皮损外观和分布、疼痛、创伤/水体/动物暴露', '软组织影像、伤口、脓液、活检与培养'],
    outputs: ['皮肤软组织综合征与具体候选', '深部采样、外科紧急性和模拟病提示'],
    triggers: ['皮疆、蜚皮癖、伤口、不成比例疼痛、水体/动物入口时 selected'],
  },
  {
    roleId: 'clinical_virology_molecular', group: 'dynamic', titleZh: '临床病毒学与分子诊断专家', titleEn: 'Clinical Virology and Molecular Diagnostics Expert', maturity: 'implemented',
    responsibility: '解读PCR/多重面板、病毒载量、血清学和基因组检测窗口，区分活动感染、再激活、潜伏与偶然检出。',
    inputs: ['病毒PCR/抗原/抗体/载量、采样时间与标本部位', '免疫状态、综合征、抗病毒治疗与疫苗史'],
    outputs: ['具体病毒型别候选与检测解读', '窗口期、再激活/偶然检出反证及复查建议'],
    triggers: ['病毒样综合征、免疫抑制、已回/待回分子结果或疑似再激活时 selected'],
  },
  {
    roleId: 'healthcare_device_infection', group: 'dynamic', titleZh: '医疗相关与器械感染专家', titleEn: 'Healthcare-associated and Device Infection Expert', maturity: 'implemented',
    responsibility: '围绕导管、人工瓣膜、心脏器械、假体、引流管和近期医疗暴露，判断生物膜、污染、定植与耐药风险。',
    inputs: ['住院/手术/透析/护理暴露、器械类型和留置时间', '成对血培养、导管培养、局部征象和耐药史'],
    outputs: ['器械相关感染可能性与候选', '污染/定植判定、器械处置与复采需求'],
    triggers: ['中心管、尿管、呼吸机、心脏/骨科器械、透析或近期医疗暴露时 selected'],
  },
]

export const WORKFLOW_MEMORY_LAYERS = [
  { title: '患者证据账本', en: 'Patient evidence ledger', detail: '只属于当前病例，保存原文片段、双时间、否定、待回和冲突；不可被模型改写。', maturity: 'partial' as WorkflowMaturity },
  { title: '病原体假设账本', en: 'Pathogen hypothesis ledger', detail: '记录每个候选如何出现、被哪些证据支持或削弱、排名为何变化；不保存隐藏思维链。', maturity: 'planned' as WorkflowMaturity },
  { title: '公共知识缓存', en: 'Public knowledge cache', detail: '跨病例复用文献、指南和公共卫生资料，但绝不包含病例原文或患者标识。', maturity: 'partial' as WorkflowMaturity },
  { title: '受治理病例库', en: 'Governed case bank', detail: 'DR.ECC与MIMIC只在本地检索，患者级隔离；返回相似点与关键差异，而不是复制病例。', maturity: 'planned' as WorkflowMaturity },
]

export const WORKFLOW_DESIGN_EVIDENCE = [
  { value: '多路', label: '异质候选召回', detail: '临床专家、结构化模型、病例库与外部知识分别提名，避免单一模型一次猜答案。' },
  { value: '双向', label: '支持与反证检索', detail: '每个候选分别寻找支持、反对和替代解释，减少确认偏倚。' },
  { value: '一次', label: '有限修订', detail: '只有合同或审稿发现明确问题时才修订一次，防止无限反思。' },
  { value: '双库', label: 'DR.ECC与MIMIC验证计划', detail: '先在DR.ECC开发与时间外验证，再冻结系统并在MIMIC做地域外部验证。' },
]

export const WORKFLOW_GOVERNANCE = [
  '完整病例只发送给用户明确选择且符合数据边界的模型；外部检索只接收去标识化概念。',
  '每次运行冻结Agent、工具、模型、术语表、调用预算与执行图；未运行节点不产生伪结果。',
  '开发模式记录边界但不中断推演；未来严格临床模式的发布和安全裁决保持独立。',
]
